{
 "title": "Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Uptime",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg(up{namespace=\"default\", service=~\"backend-service|frontend-service\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(flask_http_request_total{namespace=\"default\", status=~\"404|500|400\"}) / sum(flask_http_request_total{namespace=\"default\", status=~\"200\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tracing ALL",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "operation": "errortrace", "service": "backend" }
   ]
  },
  {
   "title": "40x 50x Error",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "flask_http_request_total{container=~\"frontend|backend\", status=~\"404|500|400\", namespace=\"default\", endpoint=~\"backend|frontend\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}